import { makeStyles, tokens } from "@fluentui/react-components";

export const useChatPanelStyles = makeStyles({
  chatPanel: {
    flex: "0 0 38%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
    borderLeft: `1px solid ${tokens.colorNeutralStroke2}`,
    minWidth: "320px",
  },
  chatHeader: {
    display: "flex",
    flexDirection: "column",
    padding: "14px 20px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: "white",
    flexShrink: 0,
  },
  chatTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#111827",
  },
  chatSubtitle: {
    fontSize: "12px",
    color: "#6b7280",
    marginTop: "2px",
  },
  chatMessages: {
    flex: 1,
    overflow: "auto",
    padding: "20px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    backgroundColor: "#fafafa",
  },
  message: {
    display: "flex",
    gap: "10px",
    alignItems: "flex-end",
  },
  messageContent: {
    flex: 1,
    maxWidth: "80%",
  },
  userMessageContent: {
    flex: 1,
    display: "flex",
    justifyContent: "flex-end",
  },
  messageBubble: {
    backgroundColor: "white",
    border: `1px solid #e5e7eb`,
    padding: "10px 14px",
    borderRadius: "14px 14px 14px 4px",
    fontSize: "14px",
    lineHeight: "1.55",
    color: "#111827",
    display: "inline-block",
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
  },
  userMessage: {
    backgroundColor: "#7C3AED",
    border: "none",
    color: "white",
    borderRadius: "14px 14px 4px 14px",
    boxShadow: "0 1px 3px rgba(124,58,237,0.25)",
  },
  aiAvatar: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    background: "#7C3AED",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "11px",
    fontWeight: "700",
    color: "white",
    flexShrink: 0,
  },
  suggestedQuestions: {
    display: "none",
  },
  suggestedQuestion: {
    display: "none",
  },
  chatInput: {
    padding: "14px 16px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: "white",
    flexShrink: 0,
  },
  inputContainer: {
    display: "flex",
    gap: "8px",
    alignItems: "flex-end",
  },
  textInput: {
    flex: 1,
  },
  sendButton: {
    minWidth: "40px",
    height: "40px",
    flexShrink: 0,
  },
  emptyState: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "40px 24px",
    textAlign: "center",
  },
  emptyStateTitle: {
    fontSize: "16px",
    fontWeight: "600",
    marginBottom: "8px",
    color: "#111827",
  },
  emptyStateText: {
    fontSize: "13px",
    color: "#6b7280",
    lineHeight: "1.55",
  },
});
