org: noel4ver
service: chatwpdf-be

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION}
  timeout: 300

  environment:
    NODE_ENV: ${env:NODE_ENV, "development"}
    DATABASE_URL: ${env:DATABASE_URL, ''}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    PINECONE_API_KEY: ${env:PINECONE_API_KEY, ''}
    PINECONE_INDEX_NAME: ${env:PINECONE_INDEX_NAME, ''}
    SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN, ''}
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET, ''}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:AWS_S3_BUCKET}/*

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - aws-sdk
      - "@aws-sdk/*"
    target: node20
    platform: node
    external:
      - pg
      - "@prisma/client/runtime/query_compiler_fast_bg.postgresql.js"
      - "@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.js"

custom:
  serverless-offline:
    httpPort: 8080
    noPrependStageInUrl: true
    lamdaTimeout: 300
    noTimeout: true

functions:
  api:
    handler: src/index.handler
    role: arn:aws:iam::${aws:accountId}:role/lambdaBasicExecutionRole
    events:
      - httpApi: "*"

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!src/**"
    - "!.git/**"
    - "!*.md"
    - "!tsconfig.json"
    - "!prisma/**"
    - "node_modules/@prisma/client/runtime/query_compiler_fast_bg.postgresql.js"
    - "node_modules/@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.js"
